config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  get '/redirect', to: 'auth#redirect', as: 'redirect'
  get '/oauth2callback', to: 'auth#callback', as: 'callback'
  get '/calendars', to: 'auth#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'auth#events', as: 'events', calendar_id: /[^\/]+/
  resource :user 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth_controller.rb
class AuthController < ApplicationController

  def redirect
    client = Signet::OAuth2::Client.new(client_options)
    redirect_to client.authorization_uri.to_s
  end


  def callback
    client = Signet::OAuth2::Client.new(client_options)
    client.code = params[:code]
    response = client.fetch_access_token!
    session[:authorization] = response
    redirect_to calendars_url
  end


  def calendars
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    @calendar_list = service.list_calendar_lists
    $calendars = @calendar_list
    redirect_to '/'
  rescue Google::Apis::AuthorizationError
    response = client.refresh!
    session[:authorization] = session[:authorization].merge(response)
    retry
  end

  def events
      client = Signet::OAuth2::Client.new(client_options)
      client.update!(session[:authorization])

      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = client

      @event_list = service.list_events(params[:calendar_id])
      $events = @event_list
      redirect_to '/'
  end

  private

  def client_options
    {
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR_READONLY,
      redirect_uri: callback_url
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Model

  attr_accessor(
    :email
  )

  private

  def create_user
    # ...
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET request for / (homepage)
  def home

  end

end

app/controllers/users_controller.rb
# app/controllers/registration_controller.rb
class Users < ActiveRecord::Base
  # Form validations
  validates :email, presence: true

  # GET to /users/:user_email
  def show
    @user = User.find( params[:email] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_event_form.erb
<%= link_to "See events", events_path(:calendar_id), class: "button btn btn-primary" %>
<% if (defined?($events.items)) %>
  <ul>
    <% $events.items.each do |event| %>
      <li><%= event.summary %> (<%= event.id %>)</li>
    <% end %>
  </ul>
<% end %>

app/views/pages/_form.html.erb
<%= form_with model: @user, url: users_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    <%= f.submit "Create", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="text-center container-fluid">
  <h1>Calapp</h1>
  <h3>Link your Google Calendar and weep at the time you spend in meetings</h3>
</div>
<div>
  <div class="container">
    <div class="row text-center">
      <%= link_to "Authorise your Calendar", redirect_path, class: "button btn btn-primary" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6 ">
      <div class="well">
        <h2 class="text-center">List of Calendars</h2>
        <ul>
            <%= link_to "See calendar list", calendars_path, class: "button btn btn-primary" %>
            <% if (defined?($calendars.items)) %>
              <ul>
              <% $calendars.items.each do |calendar| %>
                <li><%= calendar.summary %> (<%= calendar.id %>)</li>
              <% end %>
              </ul>
            <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">List of Events</h2>
        <ul>
            <p>Enter your email</p>

            <!-- To capture their email -->
            <%= form_with model: User.new do |form| %>
              <%= form.text_field :email %>
            <% end %>

            <!-- To make a request for the events -->
            <%= link_to "See events", events_path(:calendar_id => user_email), class: "button btn btn-primary" %>
            <% if (defined?($events.items)) %>
              <ul>
                <% $events.items.each do |event| %>
                  <li><%= event.summary %> (<%= event.id %>)</li>
                <% end %>
              </ul>
            <% end %>

        </ul>
      </div>
    </div>
</div>